## Read and Show Image

In [16]:
import cv2 
import numpy as np
import os

In [ ]:
img=cv2.imread(r"Images\img1.jpg")                   # Read the Image 
cv2.imshow("Read Image1",img)                        # Image Show
cv2.waitKey(0)                                      # Image Frame wait time -ms and 0 pass keyboard any key press 
cv2.destroyAllWindows()                             # All Windows close
#cv2.destroyWindow()                                 # Only One window close


In [18]:
img=cv2.imread(r"Images\img2.jpg")                   # Read the Image 
cv2.imshow("Read Image2",img)                        # Image Show
cv2.waitKey(0)                                      # Image Frame wait time -ms and 0 pass keyboard any key press 
cv2.destroyAllWindows()                             # All Windows close
#cv2.destroyWindow()                                 # Only One window close

In [19]:
img=cv2.imread(r"Images\img3.jpg")                   # Read the Image 
cv2.imshow("Read Image3",img)                        # Image Show
cv2.waitKey(0)                                      # Image Frame wait time -ms and 0 pass keyboard any key press 
cv2.destroyAllWindows()                             # All Windows close
#cv2.destroyWindow()                                 # Only One window close

## Resize and Slide Showing

In [20]:
image=cv2.imread(r"Images\img3.jpg")
re_Image=cv2.resize(image,(500,300))
cv2.imshow("Image 3",re_Image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
v = np.array([[1,2,3,1,2,3]])
np.hstack((v,v))


array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [22]:
img = cv2.imread(r"Images\img3.jpg")
print(img)  #RGB

[[[117 113 119]
  [110 106 111]
  [ 98  94  99]
  ...
  [123 141 152]
  [122 138 150]
  [122 138 150]]

 [[119 115 121]
  [109 105 110]
  [ 94  91  93]
  ...
  [123 141 152]
  [124 140 152]
  [125 141 153]]

 [[113 109 114]
  [101  97 102]
  [ 88  85  87]
  ...
  [122 140 151]
  [125 141 153]
  [128 144 156]]

 ...

 [[124 144 162]
  [122 142 160]
  [122 142 160]
  ...
  [109 120 134]
  [108 119 133]
  [109 120 134]]

 [[124 144 162]
  [123 143 161]
  [122 142 160]
  ...
  [109 120 134]
  [107 118 132]
  [107 118 132]]

 [[124 144 162]
  [124 144 162]
  [123 143 161]
  ...
  [109 120 134]
  [107 118 132]
  [105 116 130]]]


In [23]:
image=cv2.imread(r"Images\img2.jpg")
re_Image=cv2.resize(image,(300,300))
h=np.hstack((re_Image,re_Image,re_Image))
v=np.vstack((h,h))


cv2.imshow("Image 2",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Slide Show

In [25]:
list_name = os.listdir(r"C:\Users\Vikas\Desktop\OpenCV\Images")
list_name

['img1.jpg',
 'img2.jpg',
 'img3.jpg',
 'img4.jpg',
 'img5.jpg',
 'img6.jpg',
 'img7.jpg']

In [31]:
import cv2
import os

# Path to the image folder
path = r"C:\Users\Vikas\Desktop\OpenCV\Images"

# Get list of all image file names
list_name = os.listdir(path)

# Loop through each image
for name in list_name:
    img_path = os.path.join(path, name)  # Safer than manually joining
    img = cv2.imread(img_path)

    if img is not None:
        img = cv2.resize(img, (400, 400))  # Resize to 400x400
        cv2.imshow("Slide Show", img)
        cv2.waitKey(2000)  # Show image for 2 seconds
    else:
        print(f"Failed to load {img_path}")

cv2.destroyAllWindows()
